spring:
  cloud:
    openfeign:
      client:
        config:
          billing:
            url: http://localhost:8765/billing
          storage:
            url: http://localhost:8765/storage

shop:
  account:
    number: 3
